export const LOAD_USER_INFO = 'LOAD_USER_INFO';
export const LOAD_OUTLET_LIST = 'LOAD_OUTLET_LIST';
export const LOAD_MENU_ITEMS = 'LOAD_MENU_ITEMS';
export const LOAD_MENU_ITEM_DETAILS = 'LOAD_MENU_ITEM_DETAILS';
export const LOAD_CHECKED_ITEMS = 'LOAD_CHECKED_ITEMS';
export const LOAD_ACTIVE_OUTLET = 'LOAD_ACTIVE_OUTLET';
